### ISSUE TITLE
Get records in other languages than default language

### ISSUE THREAD

**Issue by zappzarapp** [bendash/json_api#1]
Is it possible to get translated records? I tried it out but i'm not sure if and how this is possible. 

I have two records (uid:1, sys_language_uid:0 - uid:2;sys_language_uid:8) 

    /routing/json_api/single/Namespace-extkey-Promotion/1
    /routing/json_api/single/Namespace-extkey-Promotion/2
    /routing/json_api/single/Namespace-extkey-Promotion/2&L=8
all return  the default record with uid:1 although i request the uid 2: 

    {"title":"title","uid":1}

Also the list action 

    /routing/json_api/list/Namespace-extkey-Promotion?limit=10&L=8
    /routing/json_api/list/Namespace-extkey-Promotion?limit=10

returns the same result although one record is translated to sys_language_uid 8

    [{"title":"title","uid":1},{"title":"promo 2","uid":3}]

**Comment by bendash** [comment]
You may want to have a look at the documentation of the routing extension, on which the json_api depends.

https://docs.typo3.org/typo3cms/extensions/routing/DeveloperManual/Index.html#localization

In short words - adding an id GET Parameter should solve your problem.

**Comment by zappzarapp** [comment]
Great, thanks for the answer.

    /routing/json_api/single/Namespace-extkey-Promotion/2?id=84&L=8i
    /routing/json_api/list/Namespace-extkey-Promotion/?id=84&L=8&limit=100

returns the translated records (where 84 is the root page of  my site)
